# Generated by Django 4.1 on 2022-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest1',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Photography', 'Photography'), ('Cinematography', 'Cinematography'), ('Movies', 'Movies'), ('Dance', 'Dance')], max_length=20),
        ),
    ]
