# Generated by Django 4.1 on 2022-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_interest_interest1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest1',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Photography', 'Photography'), ('Cinematography', 'Cinematography'), ('Movies', 'Movies'), ('Dance', 'Dance')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
