# Generated by Django 4.1 on 2022-08-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_interest_bio_alter_interest_interest1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest1',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Photography', 'Photography'), ('Cinematography', 'Cinematography'), ('Movies', 'Movies'), ('Dance', 'Dance')], max_length=20),
        ),
    ]
