# Generated by Django 4.1 on 2022-09-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_interest_interest1'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_no',
            field=models.IntegerField(default=0),
        ),
    ]
