# Generated by Django 4.1 on 2022-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_interest_interest_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='another_test',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
