# Generated by Django 4.1 on 2022-09-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_interest_another_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='another_test',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='bio',
        ),
    ]
