# Generated by Django 4.1 on 2022-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_interest_another_test_remove_interest_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
