# Generated by Django 4.1 on 2022-09-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_interest_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest1',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Photography', 'Photography'), ('Cinematography', 'Cinematography'), ('Movies', 'Movies'), ('Dance', 'Dance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
