# Generated by Django 4.1 on 2022-09-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_interest_interest1_alter_interest_interest_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_no',
            field=models.IntegerField(default=0),
        ),
    ]
