# Generated by Django 4.1 on 2022-09-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_interest_interest_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='interest_no',
        ),
    ]
