# Generated by Django 4.1 on 2022-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_interest_interest_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(default='image/default.png', upload_to='images/'),
        ),
    ]
