# Generated by Django 4.1.2 on 2022-10-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_profile_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
