# Generated by Django 4.1.7 on 2023-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_profile_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(default='https://i.ibb.co/zFLYHPb/default.png', upload_to='images/'),
        ),
    ]
