# Generated by Django 4.1.7 on 2023-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_profile_display_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='interest1',
        ),
        migrations.AddField(
            model_name='interest',
            name='interest',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
