# Generated by Django 4.1.7 on 2023-03-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='incoming',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='outgoing',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
