# Generated by Django 4.1.7 on 2023-03-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_friend_incoming_friend_outgoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='outgoing',
        ),
    ]
