# Generated by Django 4.1.7 on 2023-03-25 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_remove_friend_incoming_remove_friend_outgoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='incoming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='outgoing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to=settings.AUTH_USER_MODEL),
        ),
    ]
